/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _DT_BINDINGS_MEMORY_MT6765_LARB_PORT_H_
#define _DT_BINDINGS_MEMORY_MT6765_LARB_PORT_H_

#include <dt-bindings/memory/mtk-memory-port.h>

#define M4U_LARB0_ID	0
#define M4U_LARB1_ID	1
#define M4U_LARB2_ID	2
#define M4U_LARB3_ID	3

/* larb0 */
#define M4U_PORT_DISP_OVL0		MTK_M4U_ID(M4U_LARB0_ID, 0)
#define M4U_PORT_DISP_OVL0_2L		MTK_M4U_ID(M4U_LARB0_ID, 1)
#define M4U_PORT_DISP_RDMA0		MTK_M4U_ID(M4U_LARB0_ID, 2)
#define M4U_PORT_DISP_WDMA0		MTK_M4U_ID(M4U_LARB0_ID, 3)
#define M4U_PORT_MDP_RDMA0		MTK_M4U_ID(M4U_LARB0_ID, 4)
#define M4U_PORT_MDP_WDMA0		MTK_M4U_ID(M4U_LARB0_ID, 5)
#define M4U_PORT_MDP_WROT0		MTK_M4U_ID(M4U_LARB0_ID, 6)
#define M4U_PORT_DISP_FAKE0		MTK_M4U_ID(M4U_LARB0_ID, 7)

/* larb1 */
#define M4U_PORT_VENC_RCPU		MTK_M4U_ID(M4U_LARB1_ID, 0)
#define M4U_PORT_VENC_REC		MTK_M4U_ID(M4U_LARB1_ID, 1)
#define M4U_PORT_VENC_BSDMA		MTK_M4U_ID(M4U_LARB1_ID, 2)
#define M4U_PORT_VENC_SV_COMV		MTK_M4U_ID(M4U_LARB1_ID, 3)
#define M4U_PORT_VENC_RD_COMV		MTK_M4U_ID(M4U_LARB1_ID, 4)
#define M4U_PORT_JPGENC_RDMA		MTK_M4U_ID(M4U_LARB1_ID, 5)
#define M4U_PORT_JPGENC_BSDMA		MTK_M4U_ID(M4U_LARB1_ID, 6)
#define M4U_PORT_VENC_CUR_LUMA		MTK_M4U_ID(M4U_LARB1_ID, 7)
#define M4U_PORT_VENC_CUR_CHROMA	MTK_M4U_ID(M4U_LARB1_ID, 8)
#define M4U_PORT_VENC_REF_LUMA		MTK_M4U_ID(M4U_LARB1_ID, 9)
#define M4U_PORT_VENC_REF_CHROMA	MTK_M4U_ID(M4U_LARB1_ID, 10)

/* larb2 */
#define M4U_PORT_CAM_IMGI		MTK_M4U_ID(M4U_LARB2_ID, 0)
#define M4U_PORT_CAM_IMG2O		MTK_M4U_ID(M4U_LARB2_ID, 1)
#define M4U_PORT_CAM_IMG3O		MTK_M4U_ID(M4U_LARB2_ID, 2)
#define M4U_PORT_CAM_VIPI		MTK_M4U_ID(M4U_LARB2_ID, 3)
#define M4U_PORT_CAM_LCEI		MTK_M4U_ID(M4U_LARB2_ID, 4)
#define M4U_PORT_CAM_FD_RP		MTK_M4U_ID(M4U_LARB2_ID, 5)
#define M4U_PORT_CAM_FD_WR		MTK_M4U_ID(M4U_LARB2_ID, 6)
#define M4U_PORT_CAM_FD_RB		MTK_M4U_ID(M4U_LARB2_ID, 7)
#define M4U_PORT_CAM_DPE_RDMA		MTK_M4U_ID(M4U_LARB2_ID, 8)
#define M4U_PORT_CAM_DPE_WDMA		MTK_M4U_ID(M4U_LARB2_ID, 9)
#define M4U_PORT_CAM_RSC_RDMA		MTK_M4U_ID(M4U_LARB2_ID, 10)
#define M4U_PORT_CAM_RSC_WDMA		MTK_M4U_ID(M4U_LARB2_ID, 11)

/* larb3 */
#define M4U_PORT_CAM_IMGO		MTK_M4U_ID(M4U_LARB3_ID, 0)
#define M4U_PORT_CAM_RRZO		MTK_M4U_ID(M4U_LARB3_ID, 1)
#define M4U_PORT_CAM_AAO		MTK_M4U_ID(M4U_LARB3_ID, 2)
#define M4U_PORT_CAM_AFO		MTK_M4U_ID(M4U_LARB3_ID, 3)
#define M4U_PORT_CAM_LSCI0		MTK_M4U_ID(M4U_LARB3_ID, 4)
#define M4U_PORT_CAM_LSCI1		MTK_M4U_ID(M4U_LARB3_ID, 5)
#define M4U_PORT_CAM_PDO		MTK_M4U_ID(M4U_LARB3_ID, 6)
#define M4U_PORT_CAM_BPCI		MTK_M4U_ID(M4U_LARB3_ID, 7)
#define M4U_PORT_CAM_LCSO		MTK_M4U_ID(M4U_LARB3_ID, 8)
#define M4U_PORT_CAM_RSSO_A		MTK_M4U_ID(M4U_LARB3_ID, 9)
#define M4U_PORT_CAM_RSSO_B		MTK_M4U_ID(M4U_LARB3_ID, 10)
#define M4U_PORT_CAM_UFEO		MTK_M4U_ID(M4U_LARB3_ID, 11)
#define M4U_PORT_CAM_SOC0		MTK_M4U_ID(M4U_LARB3_ID, 12)
#define M4U_PORT_CAM_SOC1		MTK_M4U_ID(M4U_LARB3_ID, 13)
#define M4U_PORT_CAM_SOC2		MTK_M4U_ID(M4U_LARB3_ID, 14)
#define M4U_PORT_CAM_CCUI		MTK_M4U_ID(M4U_LARB3_ID, 15)
#define M4U_PORT_CAM_CCUO		MTK_M4U_ID(M4U_LARB3_ID, 16)
#define M4U_PORT_CAM_CACI		MTK_M4U_ID(M4U_LARB3_ID, 17)
#define M4U_PORT_CAM_RAWI_A		MTK_M4U_ID(M4U_LARB3_ID, 18)
#define M4U_PORT_CAM_RAWI_B		MTK_M4U_ID(M4U_LARB3_ID, 19)
#define M4U_PORT_CAM_CCUG		MTK_M4U_ID(M4U_LARB3_ID, 20)

#endif
